#pragma once
#include <binary_relational_ops.h>
#include <minterval.h>
#include <mpredicate.h>
#include <msimpleop.h>
#include <msince.h>
#include <mterm.h>
#include <operator_types.h>
#include <unary_temp_ops.h>
