#pragma once
#include <staticmon/operators/detail/binary_relational_ops.h>
#include <staticmon/operators/detail/minterval.h>
#include <staticmon/operators/detail/mpredicate.h>
#include <staticmon/operators/detail/msimpleop.h>
#include <staticmon/operators/detail/msince.h>
#include <staticmon/operators/detail/mterm.h>
#include <staticmon/operators/detail/operator_types.h>
#include <staticmon/operators/detail/unary_temp_ops.h>
#include <staticmon/operators/detail/verdict_printer.h>
#include <staticmon/operators/detail/mrelops.h>
#include <staticmon/operators/detail/aggregations.h>
